### ISSUE TITLE
tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False) 报错麻烦看看，多谢！

### ISSUE THREAD

**Issue by hopeforus** [Neutralzz/BiLLa#20]
用你推荐的程序，出现如下错误： tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
模型合并后没有问题。

Traceback (most recent call last):
File "", line 1, in
File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 642, in from_pretrained
tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 486, in get_tokenizer_config
resolved_config_file = cached_file(
File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
resolved_file = hf_hub_download(
File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
validate_repo_id(arg_value)
File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
raise HFValidationError(
huggingface_hub.utils.validators.HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/BiLLa-7B-SFT'.

**Comment by Neutralzz** [comment]
huggingface_hub.utils.validators.HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/BiLLa-7B-SFT'.
报错信息里已经写了，可能需要把model_path写成明显是本地路径的格式，或者把'-'替换成其他符号。

**Comment by hopeforus** [comment]
把路径名称写完整，而且修改了，还是报错：）
>>> model_path = "/home/hope/work/modelsall/BiLLa7BSFT"
>>> tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

**Comment by hopeforus** [comment]
已经解决，是模型配置文件错误
