### ISSUE TITLE
请大佬帮忙解决tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)对错误，困惑多日了

### ISSUE THREAD

**Issue by hopeforus** [Neutralzz/BiLLa#26]
逐条执行：
>>> import torch
>>> from transformers import AutoTokenizer, AutoModelForCausalLM
>>> model_path = "\home\hope\work\modelsall\BiLLa7BSFT"
>>> tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
报错为：Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1841, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

模型转换过程没问题，原始模型lamma7b可以在fastchat中正常运行，转换后的路径为：\home\hope\work\modelsall\BiLLa7BSFT，ununtu20系统，transformer 4.28.1 网上查了半天没有这个错误

**Comment by Neutralzz** [comment]
这问题没遇到过。。看着问题好像在sentencepiece

**Comment by hopeforus** [comment]
难道是我模型合并的问题，大佬有合并好的模型可以下载试用一下吗？

**Comment by Neutralzz** [comment]
你这个报错的信息很明显跟模型参数没有关系

**Comment by hopeforus** [comment]
嗯 模型转换的数字是对的，奇怪了，感觉是目录加载的问题，换了很多次也不行，还有其他的加载方式吗？ fastchat也是报这个错

**Comment by satisic** [comment]
> 难道是我模型合并的问题，大佬有合并好的模型可以下载试用一下吗？

转换完的权重在hg有很多吧。

**Comment by hopeforus** [comment]
是有很多其他的模型权重，我是特别想试一下楼主这个模型。我发现是加载模型描述文件的时候报错，

**Comment by hopeforus** [comment]
问题解决了，是加载模型配置文件时候出错，重新下载生成后就好了，多谢啦！我关闭这个issue，多谢各位！
